//created on: 2018-7-19
package rules.test02
import java.util.Date


/**
* 测试 date-effictive 和 date-expires
*
*/
rule "test02-date-effictive-expires-demo"
	agenda-group "test02-date-effictive-expires"
	date-effective "2018-07-19 17:05:00"
	date-expires "2018-07-19 17:06:00"
	
    when
        //conditions
    then
    	System.out.println("rule#test02-date-effictive-expires-demo: Fired, and current date is " + new Date());
end

