//created on: 2018-7-20
package rules.test04
import test04.springboot_integration.Address
import test04.springboot_integration.AddressCheckResult


rule "Postcode should be filled with exactly 5 numbers"
	
    when
        $address: Address(postcode!=null, postcode matches "([0-9]{5})")
        $checkResult: AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("规则中打印日志：校验通过!");
end

